// src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    RouterModule,
    MatButtonModule,
    MatInputModule,
    MatFormFieldModule,
    MatIconModule,
    MatDividerModule
  ],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {
  currentYear = new Date().getFullYear();
  
  // Enlaces rápidos para la navegación
  quickLinks = [
    { label: 'Home', route: '/' },
    { label: 'Shop', route: '/shop' },
    { label: 'Categories', route: '/categories' },
    { label: 'Deals', route: '/deals' },
    { label: 'About Us', route: '/about' }
  ];
  
  // Enlaces para el servicio al cliente
  customerServiceLinks = [
    { label: 'Contact Us', route: '/contact' },
    { label: 'FAQs', route: '/faqs' },
    { label: 'Shipping Policy', route: '/shipping' },
    { label: 'Returns & Exchanges', route: '/returns' },
    { label: 'Track Order', route: '/track-order' }
  ];
  
  // Redes sociales
  socialLinks = [
    { icon: 'facebook', url: 'https://facebook.com' },
    { icon: 'instagram', url: 'https://instagram.com' },
    { icon: 'twitter', url: 'https://twitter.com' },
    { icon: 'pinterest', url: 'https://pinterest.com' }
  ];
  
  // Métodos de pago
  paymentMethods = [
    { name: 'Visa', icon: 'assets/icons/visa.svg' },
    { name: 'Mastercard', icon: 'assets/icons/mastercard.svg' },
    { name: 'PayPal', icon: 'assets/icons/paypal.svg' }
  ];
  
  subscribeToNewsletter(email: string): void {
    // Implementación para suscribirse al newsletter
    console.log('Suscrito con email:', email);
  }
}

<footer class="bg-primary text-white pt-12 pb-6">
  <div class="container mx-auto px-4">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
      <!-- Logo y redes sociales -->
      <div>
        <div class="flex items-center mb-4">
          <mat-icon>shopping_bag</mat-icon>
          <span class="font-bold text-xl ml-2">BlueMart</span>
        </div>
        <p class="text-white/80 mb-4">
          Your one-stop destination for quality products at affordable prices.
        </p>
        <div class="flex gap-4">
          @for (social of socialLinks; track social.icon) {
            <button
              mat-mini-fab
              size="small"
              class="bg-white/10 text-white h-9 w-9 min-w-0"
            >
              <mat-icon>{{social.icon}}</mat-icon>
            </button>
          }
        </div>
      </div>

      <!-- Enlaces rápidos -->
      <div>
        <h3 class="font-semibold text-lg mb-4">Quick Links</h3>
        <ul class="space-y-2">
          @for (link of quickLinks; track link.label) {
            <li>
              <a [routerLink]="link.route" class="text-white/80 hover:text-white">{{link.label}}</a>
            </li>
          }
        </ul>
      </div>

      <!-- Servicio al cliente -->
      <div>
        <h3 class="font-semibold text-lg mb-4">Customer Service</h3>
        <ul class="space-y-2">
          @for (link of customerServiceLinks; track link.label) {
            <li>
              <a [routerLink]="link.route" class="text-white/80 hover:text-white">{{link.label}}</a>
            </li>
          }
        </ul>
      </div>

      <!-- Newsletter -->
      <div>
        <h3 class="font-semibold text-lg mb-4">Newsletter</h3>
        <p class="text-white/80 mb-4">
          Subscribe to receive updates, access to exclusive deals, and more.
        </p>
        <div class="flex gap-2">
          <mat-form-field appearance="fill" class="bg-white/10 rounded">
            <input matInput placeholder="Enter your email" #emailInput class="text-white" type="email">
            <mat-error>Please enter a valid email</mat-error>
          </mat-form-field>
          <button 
            mat-raised-button 
            color="accent" 
            (click)="subscribeToNewsletter(emailInput.value)"
            [disabled]="isSubscribing">
            <mat-icon *ngIf="isSubscribing" class="spinner">refresh</mat-icon>
            <span *ngIf="!isSubscribing">Subscribe</span>
          </button>
        </div>
      </div>
    </div>
    
    <mat-divider class="bg-white/20 my-6"></mat-divider>
    
    <div class="flex flex-col md:flex-row justify-between items-center">
      <p class="text-white text-sm">
        &copy; {{currentYear}} BlueMart. All rights reserved.
      </p>
      <div class="flex items-center gap-4 mt-4 md:mt-0">
        <a routerLink="/privacy" class="text-white/70 text-sm hover:text-white">Privacy Policy</a>
        <a routerLink="/terms" class="text-white/70 text-sm hover:text-white">Terms of Service</a>
        <div class="flex items-center gap-2">
          @for (payment of paymentMethods; track payment.name) {
            <img [src]="payment.icon" [alt]="payment.name" width="32" height="32">
          }
        </div>
      </div>
    </div>
  </div>
</footer>

// src/app/footer/footer.tsx
import React from "react";
import { Link, Divider, Input, Button } from "@heroui/react";
import { Icon } from "@iconify/react";

export const Footer: React.FC = () => {
  return (
    <footer className="bg-primary text-white pt-12 pb-6">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
          <div>
            <div className="flex items-center mb-4">
              <Icon icon="lucide:shopping-bag" width={24} height={24} />
              <span className="font-bold text-xl ml-2">BlueMart</span>
            </div>
            <p className="text-white/80 mb-4">
              Your one-stop destination for quality products at affordable prices.
            </p>
            <div className="flex gap-4">
              <Button isIconOnly size="sm" variant="flat" className="bg-white/10 text-white">
                <Icon icon="logos:facebook" width={18} />
              </Button>
              <Button isIconOnly size="sm" variant="flat" className="bg-white/10 text-white">
                <Icon icon="logos:instagram-icon" width={18} />
              </Button>
              <Button isIconOnly size="sm" variant="flat" className="bg-white/10 text-white">
                <Icon icon="logos:twitter" width={18} />
              </Button>
              <Button isIconOnly size="sm" variant="flat" className="bg-white/10 text-white">
                <Icon icon="logos:pinterest" width={18} />
              </Button>
            </div>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg mb-4">Quick Links</h3>
            <ul className="space-y-2">
              <li><Link href="#" className="text-white/80 hover:text-white">Home</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">Shop</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">Categories</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">Deals</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">About Us</Link></li>
            </ul>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg mb-4">Customer Service</h3>
            <ul className="space-y-2">
              <li><Link href="#" className="text-white/80 hover:text-white">Contact Us</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">FAQs</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">Shipping Policy</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">Returns & Exchanges</Link></li>
              <li><Link href="#" className="text-white/80 hover:text-white">Track Order</Link></li>
            </ul>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg mb-4">Newsletter</h3>
            <p className="text-white/80 mb-4">
              Subscribe to receive updates, access to exclusive deals, and more.
            </p>
            <div className="flex gap-2">
              <Input
                placeholder="Enter your email"
                classNames={{
                  inputWrapper: "bg-white/10 border-none",
                }}
              />
              <Button color="secondary">
                Subscribe
              </Button>
            </div>
          </div>
        </div>
        
        <Divider className="bg-white/20 my-6" />
        
        <div className="flex flex-col md:flex-row justify-between items-center">
          <p className="text-white/70 text-sm">
            &copy; 2024 BlueMart. All rights reserved.
          </p>
          <div className="flex items-center gap-4 mt-4 md:mt-0">
            <Link href="#" className="text-white/70 text-sm hover:text-white">Privacy Policy</Link>
            <Link href="#" className="text-white/70 text-sm hover:text-white">Terms of Service</Link>
            <div className="flex items-center gap-2">
              <Icon icon="logos:visa" width={32} />
              <Icon icon="logos:mastercard" width={32} />
              <Icon icon="logos:paypal" width={32} />
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};
